[package]
name = "snss"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "snss"
path = "src/snss.rs"

[dependencies]
thiserror = "2.0.11"
serde = "1.0.218"
byteorder = "1.5.0"
bitflags = "2.9.0"
fmt = "0.1.0"
