[package]
name = "snss"
version = "0.1.0"

[[bin]]
name = "snss"
path = "src/snss.rs"

[[bin]]
name = "mdview"
path = "src/view.rs"

[[bin]]
name = "memmap"
path = "src/memmap.rs"

[dependencies]
memmap2 = "0.9.0"
binary-layout = "3.2.0"
arrayref = "0.3.7"
